title: Sophia E Hwangbo
#logo: /assets/img/headshot_circle.png
#descrption:text below image
#show_downloads: true
#theme: jekyll-theme-minima

#title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
